## Numpy
linear algebra library
intel mkl or Openblas
**- similar like lists
**- efficient than lists( honda  vs turtle)
**- store data efficiently 
**- great for big numarical operations
**- Consumes less memeory 


In [ ]:
#pip install numpy, alrerady install in jupytar
**- array i.e., stack of a bread

In [3]:
import numpy as np
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape


(1, 6)

In [4]:
a=np.arange(6)

In [5]:
a


array([0, 1, 2, 3, 4, 5])

In [7]:
a2=a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [12]:
#1-d array
arr=np.array([5,5,5,])
arr

array([5, 5, 5])

In [15]:
#2-d array
arr2=np.array([arr,[2,3,1]])
arr2

array([[5, 5, 5],
       [2, 3, 1]])

In [16]:
type(arr2)

numpy.ndarray

In [17]:
len(arr2)

2

In [18]:
len(arr)

3

In [22]:
ar0=np.zeros(2)
ar0


array([0., 0.])

In [23]:
ar00=np.array([0,0])

In [24]:
ar00

array([0, 0])

In [25]:
ar01=np.ones(3)
ar01

array([1., 1., 1.])

In [27]:
ar10=np.arange(3,9)
ar10

array([3, 4, 5, 6, 7, 8])

In [29]:
ar11=np.arange(2,30,7)
ar11

array([ 2,  9, 16, 23])

In [33]:
#when u give range and specify start and end value , end value may not be exclusive like below
ar000=np.linspace(2,8,num=7)
ar000

array([2., 3., 4., 5., 6., 7., 8.])

In [3]:
import numpy as np
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
a2=np.zeros(2,dtype=np.int8)
a2

array([0, 0], dtype=int8)

In [11]:
a2=np.ones(2,dtype=np.int8)

In [12]:
a2=np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
a3=np.ones((5,2))

In [14]:
a3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])